# horizoantal pod autoscalling is single pod cant handel the traffic hpa will do the increase the number of reolicas of ur pod
# vertical auto sacalling is increase the the resouces in the same server
# u need to fallow this steps for hpa u need to install the metrix server and apche banech for request testing and resouces menctioned
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-hpa
  labels:
    kind: hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      kind: hpa
  template:
    metadata:
      labels:
        kind: hpa
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: "100m"
            memory: "150Mi"
          limits:
            cpu: "150m"
            memory: "156Mi"
---
Kind: Service
apiVersion: v1
metadata:
  name: webservice
spec:
  type: LoadBalancer
  selector:
    kind: hpa
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-hpa
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50