apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-kub-cluster
  region: ap-south-1

managedNodeGroups:
  - name: kubernetes
    instanceType: m5.large
    # your K8 node can be anytime taken back by AWS
    desiredCapacity: 3
    # created to practice EBS static provisioning
    availabilityZones:
      - ap-south-1a
    ssh:
      publicKeyName: last