apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-north-1

nodeGroups:
  - name: eks-spot-cluster
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
    availabilityZones:
      - ap-south-1a
    ssh:
      publicKeyName: last
