kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    project: roboshop
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: web
  template:
    metadata:
      labels:
        project: roboshop
        tier: web
    spec:
      containers:
      - image: nginx
        name: nginx
      nodeSelector:
        tier: web


