# node affinity its simplilar like node slelctor, nodeAffinity required during sheduling is a hard rule nodeaffinity has to mach the
# node labels if not matched u can deploye a po it wont create a pod
# based on some operators u can use as per ur requirements
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: In
            values:
            - db
  containers:
  - name: with-node-affinity
    image: nginx

