# nodeAntiAffinity its nothing but operators i menctioned as NotIn so the pod wont create on the taged node 
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: NotIn
            values:
            - web
  containers:
  - name: with-node-affinity
    image: nginx
