# docker run -p 80:80 nginx --> pull image from dockerhub and create container
kind: Pod
apiVersion: v1
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
# ---
# kind: Pod
# apiVersion: v1
# metadata:
#   name: cart
#   labels:
#     name: cart
# spec:
#   affinity:
#     podAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchExpressions:
#           - key: name
#             operator: In
#             values:
#             - mongodb
#         topologyKey: topology.kubernetes.io/zone
#   containers:
#   - image: nginx
#     name: nginx
#     ports:
#     - containerPort: 80