# docker run -p 80:80 nginx --> pull image from dockerhub and create container
kind: Pod
apiVersion: v1
metadata:
  name: web
  labels:
    app: store
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: cart
  labels:
    app: cart
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: NotIn
            values:
            - store
        topologyKey: topology.kubernetes.io/zone
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
