# useCae is like u r rinning 3 node cluster ur pod want to run 3 replicas in 3 different nodes for high availabilty 
#create a deployrmrnt set with 3 replicas and in podaffinity as per ur requirement u can give the expression
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
spec:
  selector:
    matchLabels:
      app: stores
  replicas: 3
  template:
    metadata:
      labels:
        app: stores
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - stores
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx
        image: redis:3.2-alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-site
spec:
  selector:
    matchLabels:
      app: web-stores
  replicas: 3
  template:
    metadata:
      labels:
        app: web-stores
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-stores
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: web-app
        image: nginx:1.16-alpine