# pod affinity os like where the pod1 was running ur next creating pod will go to the nonde where pod 1 was exist
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    name: catalogue
spec:
  containers:
  - name: catalogue
    image: nginx
# ---
# #So i want my cart pod where catalogue pod was runnng podAffinity
# apiVersion: v1
# kind: Pod
# metadata:
#   name: with-pod-affinity
# spec:
#   affinity:
#     podAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchExpressions:
#           - key: name
#             operator: In
#             values:
#             - catalogue
#         topologyKey: topology.kubernetes.io/zone
#   containers:
#   - name: cart
#     image: nginx
