# docker run -p 80:80 nginx --> pull image from dockerhub and create container
kind: Pod
apiVersion: v1
metadata:
  name: web
  namespace: roboshop
  labels:
    name: web
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: webs
  namespace: roboshop
  labels:
    name: webs
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - web
        topologyKey: topology.kubernetes.io/zone
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80