kind: Pod
apiVersion: v1
metadata:
  name: web
  labels:
    type: tolerations
spec:
  containers:
  - image: nginx
    name: web
  tolerations:
  - key: "project"
    value: "robo"
    operator: "Equal"
    effect: "NoSchedule"
