Kind: Service
apiVersion: v1
metadata:
  name: test
spec:
  selector:
    course: kubernetes
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx
  labels:
    course: kubernetes
spec:
  containers:
  - image: nginx
    name: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - name: debug
    image: "almalinux:8"
    command: ["sleep", "20000"]
