kind: Pod 
apiVersion: v1
metadata:
  name: nginx
  labels:
    course: kubernetes
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  selector:
    course: kubernetes
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
---
kind: Pod
apiVersion: v1
metadata: 
  name: debug
spec:
  containers:
  - image: "almalinux:8"
    name: alma
    command: ["sleep", "20000"]



