kind: Pod 
apiVersion: v1
metadata:
  name: nginx
  labels:
    course: kubernetes
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80.
# ---
# apiVersion: v1
# kind: Service
# metedata:
#   name: nginxservice
# spec:
#   selector:
#     course: kubernetes
#   ports:
#   - name: http-port
#     protocol: TCP
#     port: 80
#     targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    course: kubernetes
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80


