#Services in kubernrts it has 3 services in k8
#service is used to balaning the load and exposing the application to the outside world and its acts as a service mesh 
# clusterip: real will get more clarity
# nodeport: exposing the applocaion to outside world u can acces with ec2ip:nodeport type: NodePort
# loadbalancer: complete cloud concept aws
# how theservice eill go and connect to pod is through the pod labels has give to serive under selector section
kind: Service
apiVersion: v1
metadata:
  name: cluster-ip
  labels:
    servicetype: clusterip
spec:
  selector:
    course: kubernetes
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
kind: Pod
apiVersion: v1
metadata: 
  name: clustreip
  labels:
    name: labels
    course: kubernetes
    duration: 10days
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
---
kind: Pod
apiVersion: v1
metadata: 
  name: debug
spec:
  containers:
  - image: "almalinux:8"
    name: almalinux
    command: ["sleep", "20000"]
