kind: Service
apiVersion: v1
metadata:
  name: loadbalancer
  labels:
    servicetype: loadbalancer
spec:
  type: LoadBalancer
  selector: 
    course: kubernets
  ports: 
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80


