kind: Service
apiVersion: v1
metadata: 
  name: nodeport
  labels:
    servicetype: nodeport
spec:
  type: NodePort
  selector: 
    course: kubernetes
    duration: 6months
  ports:
  - name: http
    protocol: tcp
    port: 80
    targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: nodeport
  labels:
    course: kubernetes
    duration: 6months
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80

