apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-dynamic-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: "ebs-dynamic-sc"
---
kind: Pod
apiVersion: v1
metadata: 
  name: ebs-dynamic
  labels:
    kind: ebs-dynamic
    type: ebs
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: ebs-dynamic
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: ebs-dynamic
    persistentVolumeClaim: 
      claimName: ebs-dynamic-pvc
---
kind: Service
apiVersion: v1
metadata: 
  name: ebs-static
spec:
  type: LoadBalancer
  selector:
    kind: ebs-dynamic
    type: ebs
  ports:
  - name: htttp-port
    protocol: TCP
    port: 80
    targetPort: 80
