apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  awsElasticBlockStore:
    volumeID: "vol-09b1b008754542933"
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 18Gi
  storageClassName: ""
---
kind: Pod
apiVersion: v1
metadata:
  name: ebs-static
  labels:
    kind: storage
    type: ebs
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: staticebs
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: staticebs
    PersistentVolumeClaim:
      name: ebs-static
---
kind: Service
apiVersion: v1
metadata:
  name: ebsservice
  labels:
    kind: service
    type: ebs
spec:
  type: LoadBalancer
  selector:
    kind: storage
    type: ebs
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80






