apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  awsElasticBlockStore:
    volumeID: vol-0277b8f3df8c68baa
    fsType: ext4