kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1-service
  labels:
    service: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ingress
  template:
    metadata:
      labels:
        name: ingress
    spec:
      containers:
      - image: saivinaylt/app1:k8
        name: nginx
---
kind: Service
apiVersion: v1
metadata:
  name: app1-service
  labels:
    service: ingress
spec:
  selector:
    name: ingress
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
# Here Ingress is the resource that is capable of creating AWS ALB resource, you must provide annotations
# annotations are used to connect the external resouces you must provide annotations
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1service
  # kubernetes ingress for aws alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Environment=DEV
    alb.ingress.kubernetes.io/group.name: devopslt
spec:
  ingressClassName: alb
  rules:
  - host: "app1.devopslt.online"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: app1-service
            port:
              number: 80