# we can keep multiple containers in one pod it used for side car patteren pushing logs to extermal elk ..and 2 containers was access
#same network and storage will prove that 
kind: Pod
apiVersion: v1
metadata:
  name: multi-pod
spec:
  containers:
  - image: nginx
    name: nginx
  - image: almalinux:8
    name: alma
    command: ["sleep", "20000"]