kind: Pod
apiVersion: v1
metadata:
  name: secrets
spec:
  containers:
  - image: nginx
    name: nginx
    imagePullPolicy: Always
    env:
    - name: USER_NAME
      valueFrom:
        secretKeyRef:
          name: passwdsec
          key: username
   - name: USER_PASS
     valueFrom:
      secretKeyRf:
        key: password
        name: passwdsec
   
  

  